/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vTUKaF2Xf6R
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Author() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[100px]">Author ID</TableHead>
          <TableHead>Author Name</TableHead>
          <TableHead>Website</TableHead>
          <TableHead>Notes</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell className="font-medium">1</TableCell>
          <TableCell>John Doe</TableCell>
          <TableCell>example.com</TableCell>
          <TableCell>Admin</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">2</TableCell>
          <TableCell>Jane Smith</TableCell>
          <TableCell>smith.com</TableCell>
          <TableCell>Editor</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">3</TableCell>
          <TableCell>Michael Johnson</TableCell>
          <TableCell>johnson.com</TableCell>
          <TableCell>Author</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">4</TableCell>
          <TableCell>Emily Davis</TableCell>
          <TableCell>davis.com</TableCell>
          <TableCell>Contributor</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">5</TableCell>
          <TableCell>Chris Wilson</TableCell>
          <TableCell>wilson.com</TableCell>
          <TableCell>Subscriber</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}
