/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/x7SW7rILo0R
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function ProductPage() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[100px]">Book ID</TableHead>
          <TableHead>Title</TableHead>
          <TableHead>Author ID</TableHead>
          <TableHead>Category ID</TableHead>
          <TableHead>Publisher ID</TableHead>
          <TableHead>Publication Year</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow>
          <TableCell className="font-medium">B001</TableCell>
          <TableCell>The Alchemist</TableCell>
          <TableCell>A001</TableCell>
          <TableCell>C001</TableCell>
          <TableCell>P001</TableCell>
          <TableCell>1988</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">B002</TableCell>
          <TableCell>The Catcher in the Rye</TableCell>
          <TableCell>A002</TableCell>
          <TableCell>C002</TableCell>
          <TableCell>P002</TableCell>
          <TableCell>1951</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">B003</TableCell>
          <TableCell>To Kill a Mockingbird</TableCell>
          <TableCell>A003</TableCell>
          <TableCell>C003</TableCell>
          <TableCell>P003</TableCell>
          <TableCell>1960</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">B004</TableCell>
          <TableCell>1984</TableCell>
          <TableCell>A004</TableCell>
          <TableCell>C004</TableCell>
          <TableCell>P004</TableCell>
          <TableCell>1949</TableCell>
        </TableRow>
        <TableRow>
          <TableCell className="font-medium">B005</TableCell>
          <TableCell>The Great Gatsby</TableCell>
          <TableCell>A005</TableCell>
          <TableCell>C005</TableCell>
          <TableCell>P005</TableCell>
          <TableCell>1925</TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}
