// "use client";

import type {Metadata} from "next";
import {Inter} from "next/font/google";

import NavigationBar from "@/components/shared/navbar";
import {Toaster} from "@/components/ui/toaster";
import {SessionProvider} from "@/components/provider/next-auth-provider";

const inter = Inter({subsets: ["latin"]});
export const metadata: Metadata = {
  title: "Library Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavigationBar />
          {children}
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
